use std::path::Path;

use binary_filler_core::CoverProfile;

use crate::EmitError;

/// Render a Windows resource script for VERSIONINFO, optional icon, and manifest.
pub fn render_rc(cover: &CoverProfile, warnings: &mut Vec<String>) -> Result<String, EmitError> {
    let (file_ms, file_ls) = cover.file_version_ms_ls();
    let (prod_ms, prod_ls) = cover.product_version_ms_ls();

    let mut out = String::new();
    out.push_str("/* Generated by binary-filler-build — do not edit */\n");
    out.push_str("#include <winver.h>\n\n");

    if let Some(icon) = &cover.icon {
        if icon.is_file() {
            let icon_path = escape_rc_path(icon);
            out.push_str(&format!("1 ICON \"{icon_path}\"\n\n"));
            println!("cargo:rerun-if-changed={}", icon.display());
        } else {
            warnings.push(format!(
                "cover icon not found at {}; skipping ICON resource",
                icon.display()
            ));
        }
    }

    // Application manifest: asInvoker, common Win10+ compat.
    out.push_str(r#"1 24
BEGIN
"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>\r\n"
"<assembly xmlns=""urn:schemas-microsoft-com:asm.v1"" manifestVersion=""1.0"">\r\n"
"  <assemblyIdentity version=""1.0.0.0"" name=""CoverApp"" type=""win32""/>\r\n"
"  <trustInfo xmlns=""urn:schemas-microsoft-com:asm.v3"">\r\n"
"    <security>\r\n"
"      <requestedPrivileges>\r\n"
"        <requestedExecutionLevel level=""asInvoker"" uiAccess=""false""/>\r\n"
"      </requestedPrivileges>\r\n"
"    </security>\r\n"
"  </trustInfo>\r\n"
"  <compatibility xmlns=""urn:schemas-microsoft-com:compatibility.v1"">\r\n"
"    <application>\r\n"
"      <supportedOS Id=""{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}""/>\r\n"
"      <supportedOS Id=""{1f676c76-80e1-4239-95bb-83d0f6d0da78}""/>\r\n"
"      <supportedOS Id=""{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}""/>\r\n"
"      <supportedOS Id=""{35138b9a-5d96-4fbd-8e2d-a2440225f93a}""/>\r\n"
"      <supportedOS Id=""{e2011457-1546-43c5-a5fe-008deee3d3f0}""/>\r\n"
"    </application>\r\n"
"  </compatibility>\r\n"
"</assembly>\r\n"
END

"#);

    out.push_str("VS_VERSION_INFO VERSIONINFO\n");
    out.push_str(&format!("FILEVERSION {a},{b},{c},{d}\n", a = cover.file_version[0], b = cover.file_version[1], c = cover.file_version[2], d = cover.file_version[3]));
    out.push_str(&format!("PRODUCTVERSION {a},{b},{c},{d}\n", a = cover.product_version[0], b = cover.product_version[1], c = cover.product_version[2], d = cover.product_version[3]));
    out.push_str("FILEFLAGSMASK 0x3fL\n");
    out.push_str("FILEFLAGS 0x0L\n");
    out.push_str("FILEOS 0x40004L\n");
    out.push_str("FILETYPE 0x1L\n");
    out.push_str("FILESUBTYPE 0x0L\n");
    out.push_str("BEGIN\n");
    out.push_str("    BLOCK \"StringFileInfo\"\n");
    out.push_str("    BEGIN\n");
    out.push_str("        BLOCK \"040904B0\"\n");
    out.push_str("        BEGIN\n");
    push_string_value(&mut out, "CompanyName", &cover.company_name);
    push_string_value(&mut out, "FileDescription", &cover.file_description);
    push_string_value(&mut out, "FileVersion", &cover.file_version_string());
    push_string_value(&mut out, "InternalName", &cover.internal_name);
    push_string_value(&mut out, "LegalCopyright", &cover.legal_copyright);
    push_string_value(&mut out, "OriginalFilename", &cover.original_filename);
    push_string_value(&mut out, "ProductName", &cover.product_name);
    push_string_value(&mut out, "ProductVersion", &cover.product_version_string());
    out.push_str("        END\n");
    out.push_str("    END\n");
    out.push_str("    BLOCK \"VarFileInfo\"\n");
    out.push_str("    BEGIN\n");
    out.push_str("        VALUE \"Translation\", 0x409, 1200\n");
    out.push_str("    END\n");
    out.push_str("END\n");

    // Keep numeric versions referenced so format stays aligned with MSVC/windres expectations.
    let _ = (file_ms, file_ls, prod_ms, prod_ls);

    Ok(out)
}

fn push_string_value(out: &mut String, key: &str, value: &str) {
    out.push_str(&format!(
        "            VALUE \"{key}\", \"{value}\"\n",
        value = escape_rc_string(value)
    ));
}

fn escape_rc_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_rc_path(path: &Path) -> String {
    // windres/rc accept forward slashes; escape backslashes for safety.
    let s = path.to_string_lossy().replace('\\', "/");
    escape_rc_string(&s)
}
