use std::path::PathBuf;

use binary_filler_core::{FillPlan, ImportProfile};

/// Generate the consumer-side module included via `binary_filler::keep!()`.
pub fn render_generated(
    plan: &FillPlan,
    blob_paths: &[PathBuf],
    enable_import_anchors: bool,
) -> String {
    let mut out = String::new();
    out.push_str("// Generated by binary-filler-build — do not edit.\n\n");

    out.push_str(&format!(
        "pub const COVER_NAME: &str = \"{}\";\n",
        escape_rust_string(&plan.cover.name)
    ));
    out.push_str(&format!(
        "pub const SYNTHETIC_BLOBS: bool = {};\n",
        plan.synthetic_blobs
    ));
    out.push_str(&format!(
        "pub const BLOB_COUNT: usize = {};\n\n",
        plan.blobs.len()
    ));

    for (idx, (blob, path)) in plan.blobs.iter().zip(blob_paths.iter()).enumerate() {
        let path_lit = path.display().to_string().replace('\\', "/");
        out.push_str(&format!("// source: {}\n", blob.source));
        out.push_str(&format!("// entropy: {:.4}\n", blob.entropy));
        // LTO retention: used + never-inline keep root + runtime black_box.
        out.push_str("#[used]\n");
        out.push_str(&format!(
            "static BINARY_FILLER_BLOB_{idx}: [u8; {}] = *include_bytes!(r#\"{path_lit}\"#);\n\n",
            blob.data.len()
        ));
    }

    out.push_str("#[inline(never)]\n");
    out.push_str("fn touch_blobs() {\n");
    out.push_str("    use core::hint::black_box;\n");
    if plan.blobs.is_empty() {
        out.push_str("    let _ = black_box(0u8);\n");
    } else {
        for idx in 0..plan.blobs.len() {
            out.push_str(&format!(
                "    black_box(core::ptr::addr_of!(BINARY_FILLER_BLOB_{idx}));\n"
            ));
            out.push_str(&format!(
                "    black_box(BINARY_FILLER_BLOB_{idx}.len());\n"
            ));
            // Force a data dependency so LTO cannot prove the blob is unread.
            out.push_str(&format!(
                "    black_box(unsafe {{ core::ptr::read_volatile(BINARY_FILLER_BLOB_{idx}.as_ptr()) }});\n"
            ));
        }
    }
    out.push_str("}\n\n");

    if enable_import_anchors && plan.import_profile != ImportProfile::None {
        out.push_str(import_anchor_module(plan.import_profile));
        out.push_str("\n#[inline(never)]\n");
        out.push_str("fn touch_imports() {\n");
        out.push_str("    imports::touch();\n");
        out.push_str("}\n\n");
    } else {
        out.push_str("#[inline(never)]\n");
        out.push_str("fn touch_imports() {}\n\n");
    }

    // Public never-inline root: survives cross-crate LTO better than a tiny inline keep().
    out.push_str("#[inline(never)]\n");
    out.push_str("#[cold]\n");
    out.push_str("pub fn keep() {\n");
    out.push_str("    touch_blobs();\n");
    out.push_str("    touch_imports();\n");
    out.push_str("}\n");

    out
}

fn import_anchor_module(profile: ImportProfile) -> &'static str {
    match profile {
        ImportProfile::None => "",
        ImportProfile::Gui => GUI_IMPORTS,
        ImportProfile::DesktopApp => DESKTOP_IMPORTS,
    }
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

const GUI_IMPORTS: &str = r#"
#[cfg(windows)]
mod imports {
    use core::hint::black_box;

    #[link(name = "user32")]
    unsafe extern "system" {
        fn GetDesktopWindow() -> isize;
        fn GetForegroundWindow() -> isize;
        fn GetActiveWindow() -> isize;
    }

    #[link(name = "gdi32")]
    unsafe extern "system" {
        fn GetStockObject(i: i32) -> isize;
    }

    #[link(name = "shell32")]
    unsafe extern "system" {
        fn SHGetFolderPathW(
            hwnd: isize,
            csidl: i32,
            token: isize,
            flags: u32,
            path: *mut u16,
        ) -> i32;
    }

    #[link(name = "comctl32")]
    unsafe extern "system" {
        fn InitCommonControls();
    }

    #[inline(never)]
    pub fn touch() {
        // Function items as raw pointers force IAT entries without calling.
        black_box(GetDesktopWindow as *const ());
        black_box(GetForegroundWindow as *const ());
        black_box(GetActiveWindow as *const ());
        black_box(GetStockObject as *const ());
        black_box(SHGetFolderPathW as *const ());
        black_box(InitCommonControls as *const ());
    }
}

#[cfg(not(windows))]
mod imports {
    pub fn touch() {}
}
"#;

const DESKTOP_IMPORTS: &str = r#"
#[cfg(windows)]
mod imports {
    use core::hint::black_box;

    #[link(name = "user32")]
    unsafe extern "system" {
        fn GetDesktopWindow() -> isize;
        fn MessageBoxW(hwnd: isize, text: *const u16, caption: *const u16, ty: u32) -> i32;
    }

    #[link(name = "gdi32")]
    unsafe extern "system" {
        fn GetStockObject(i: i32) -> isize;
    }

    #[link(name = "shell32")]
    unsafe extern "system" {
        fn SHGetFolderPathW(
            hwnd: isize,
            csidl: i32,
            token: isize,
            flags: u32,
            path: *mut u16,
        ) -> i32;
    }

    #[link(name = "comctl32")]
    unsafe extern "system" {
        fn InitCommonControls();
    }

    #[link(name = "ole32")]
    unsafe extern "system" {
        fn CoInitializeEx(pv: *mut core::ffi::c_void, dw: u32) -> i32;
    }

    #[link(name = "oleaut32")]
    unsafe extern "system" {
        fn SysAllocString(s: *const u16) -> *mut u16;
    }

    #[link(name = "advapi32")]
    unsafe extern "system" {
        fn RegOpenKeyExW(
            key: isize,
            sub: *const u16,
            reserved: u32,
            access: u32,
            result: *mut isize,
        ) -> i32;
    }

    #[inline(never)]
    pub fn touch() {
        black_box(GetDesktopWindow as *const ());
        black_box(MessageBoxW as *const ());
        black_box(GetStockObject as *const ());
        black_box(SHGetFolderPathW as *const ());
        black_box(InitCommonControls as *const ());
        black_box(CoInitializeEx as *const ());
        black_box(SysAllocString as *const ());
        black_box(RegOpenKeyExW as *const ());
    }
}

#[cfg(not(windows))]
mod imports {
    pub fn touch() {}
}
"#;
